CREATE EVENT `checkout's_daily_close` 
ON SCHEDULE EVERY 1 DAY STARTS (CURRENT_DATE() + 1) 
ON COMPLETION PRESERVE 
DO 
UPDATE `registros` 
SET `hora_egreso` = ((CURRENT_DATE() - 1) + INTERVAL 23 HOUR + INTERVAL 59 MINUTE + INTERVAL 59 SECOND) 
WHERE `hora_egreso` IS NULL;